//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidoClient.PedidoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/PedidoService")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PedidoClient.PedidoServiceReference.Produto[] ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PedidoClient.PedidoServiceReference.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/PedidoService")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoServiceReference.IPedidoService")]
    public interface IPedidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/CriarPedido", ReplyAction="http://tempuri.org/IPedidoService/CriarPedidoResponse")]
        void CriarPedido(PedidoClient.PedidoServiceReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/CriarPedido", ReplyAction="http://tempuri.org/IPedidoService/CriarPedidoResponse")]
        System.Threading.Tasks.Task CriarPedidoAsync(PedidoClient.PedidoServiceReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidos", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosResponse")]
        PedidoClient.PedidoServiceReference.Pedido[] ListarPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidos", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosResponse")]
        System.Threading.Tasks.Task<PedidoClient.PedidoServiceReference.Pedido[]> ListarPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/BuscarPedidoPorId", ReplyAction="http://tempuri.org/IPedidoService/BuscarPedidoPorIdResponse")]
        PedidoClient.PedidoServiceReference.Pedido BuscarPedidoPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/BuscarPedidoPorId", ReplyAction="http://tempuri.org/IPedidoService/BuscarPedidoPorIdResponse")]
        System.Threading.Tasks.Task<PedidoClient.PedidoServiceReference.Pedido> BuscarPedidoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarPedido", ReplyAction="http://tempuri.org/IPedidoService/AtualizarPedidoResponse")]
        void AtualizarPedido(PedidoClient.PedidoServiceReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarPedido", ReplyAction="http://tempuri.org/IPedidoService/AtualizarPedidoResponse")]
        System.Threading.Tasks.Task AtualizarPedidoAsync(PedidoClient.PedidoServiceReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarStatus", ReplyAction="http://tempuri.org/IPedidoService/AtualizarStatusResponse")]
        void AtualizarStatus(int id, string novoStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarStatus", ReplyAction="http://tempuri.org/IPedidoService/AtualizarStatusResponse")]
        System.Threading.Tasks.Task AtualizarStatusAsync(int id, string novoStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ExcluirPedido", ReplyAction="http://tempuri.org/IPedidoService/ExcluirPedidoResponse")]
        void ExcluirPedido(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ExcluirPedido", ReplyAction="http://tempuri.org/IPedidoService/ExcluirPedidoResponse")]
        System.Threading.Tasks.Task ExcluirPedidoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoServiceChannel : PedidoClient.PedidoServiceReference.IPedidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoServiceClient : System.ServiceModel.ClientBase<PedidoClient.PedidoServiceReference.IPedidoService>, PedidoClient.PedidoServiceReference.IPedidoService {
        
        public PedidoServiceClient() {
        }
        
        public PedidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CriarPedido(PedidoClient.PedidoServiceReference.Pedido pedido) {
            base.Channel.CriarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task CriarPedidoAsync(PedidoClient.PedidoServiceReference.Pedido pedido) {
            return base.Channel.CriarPedidoAsync(pedido);
        }
        
        public PedidoClient.PedidoServiceReference.Pedido[] ListarPedidos() {
            return base.Channel.ListarPedidos();
        }
        
        public System.Threading.Tasks.Task<PedidoClient.PedidoServiceReference.Pedido[]> ListarPedidosAsync() {
            return base.Channel.ListarPedidosAsync();
        }
        
        public PedidoClient.PedidoServiceReference.Pedido BuscarPedidoPorId(int id) {
            return base.Channel.BuscarPedidoPorId(id);
        }
        
        public System.Threading.Tasks.Task<PedidoClient.PedidoServiceReference.Pedido> BuscarPedidoPorIdAsync(int id) {
            return base.Channel.BuscarPedidoPorIdAsync(id);
        }
        
        public void AtualizarPedido(PedidoClient.PedidoServiceReference.Pedido pedido) {
            base.Channel.AtualizarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task AtualizarPedidoAsync(PedidoClient.PedidoServiceReference.Pedido pedido) {
            return base.Channel.AtualizarPedidoAsync(pedido);
        }
        
        public void AtualizarStatus(int id, string novoStatus) {
            base.Channel.AtualizarStatus(id, novoStatus);
        }
        
        public System.Threading.Tasks.Task AtualizarStatusAsync(int id, string novoStatus) {
            return base.Channel.AtualizarStatusAsync(id, novoStatus);
        }
        
        public void ExcluirPedido(int id) {
            base.Channel.ExcluirPedido(id);
        }
        
        public System.Threading.Tasks.Task ExcluirPedidoAsync(int id) {
            return base.Channel.ExcluirPedidoAsync(id);
        }
    }
}
